apiVersion: v1
kind: Secret
metadata:
  name: {{ include "durable-task-scheduler.fullname" . }}-secrets
  labels:
    {{- include "durable-task-scheduler.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.dtsEmulator.enabled }}
  connectionString: {{ .Values.durableTask.connectionString | default (printf "Endpoint=http://%s-dts-emulator:%v;Authentication=None;TaskHubName=%s" (include "durable-task-scheduler.fullname" .) (int .Values.dtsEmulator.service.port) .Values.durableTask.hubName) }}
  {{- else }}
  connectionString: {{ .Values.durableTask.connectionString | default "UseDefaultDevelopment=true" }}
  {{- end }}

